[
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "<!--e57a25ab6845829454e8d69fc972939a-->\n\nThe following sections might be updated with supplementary metadata relevant to reviewers and maintainers.\n\n<!--006a51241073e994b41acfe9ec718e94-->\n### Code Coverage\nFor detailed information about the code coverage, see the [test coverage report](https://corecheck.dev/bitcoin/bitcoin/pulls/29396).\n<!--021abf342d371248e50ceaed478a90ca-->\n### Reviews\nSee [the guideline](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#code-review) for information on the review process.\n| Type | Reviewers |\n| ---- | --------- |\n| Concept ACK | [S3RK](https://github.com/bitcoin/bitcoin/pull/29396#issuecomment-1933547285) |\n\nIf your review is incorrectly listed, please react with ð to this comment and the bot will ignore it on the next update.\n<!--174a7506f384e20aa4161008e828411d-->\n### Conflicts\nReviewers, this pull request conflicts with the following ones:\n\n* [#22838](https://github.com/bitcoin/bitcoin/pull/22838) (descriptors: Be able to specify change and receiving in a single descriptor string by achow101)\n\nIf you consider this pull request important, please also help to review the conflicting pull requests. Ideally, start with the one that should be merged first.\n",
      "created_at" : "2024-02-07T07:41:56Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29396#issuecomment-1931453845",
      "id" : 1931453845,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29396",
      "node_id" : "IC_kwDOABII585zH6WV",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1931453845/reactions"
      },
      "updated_at" : "2024-02-08T08:06:36Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1931453845",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/39886733?v=4",
         "events_url" : "https://api.github.com/users/DrahtBot/events{/privacy}",
         "followers_url" : "https://api.github.com/users/DrahtBot/followers",
         "following_url" : "https://api.github.com/users/DrahtBot/following{/other_user}",
         "gists_url" : "https://api.github.com/users/DrahtBot/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/DrahtBot",
         "id" : 39886733,
         "login" : "DrahtBot",
         "node_id" : "MDQ6VXNlcjM5ODg2NzMz",
         "organizations_url" : "https://api.github.com/users/DrahtBot/orgs",
         "received_events_url" : "https://api.github.com/users/DrahtBot/received_events",
         "repos_url" : "https://api.github.com/users/DrahtBot/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/DrahtBot/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/DrahtBot/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/DrahtBot"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "```\r\ntest  2024-02-07T08:26:22.085000Z TestFramework (ERROR): JSONRPC error \r\n                                 Traceback (most recent call last):\r\n                                   File \"/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py\", line 131, in main\r\n                                     self.run_test()\r\n                                   File \"/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_bumpfee.py\", line 100, in run_test\r\n                                     test_watchonly_psbt(self, peer_node, rbf_node, dest_address)\r\n                                   File \"/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_bumpfee.py\", line 575, in test_watchonly_psbt\r\n                                     pub_rec_desc = rbf_node.getdescriptorinfo(priv_rec_desc)[\"descriptor\"]\r\n                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n                                   File \"/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/coverage.py\", line 50, in __call__\r\n                                     return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)\r\n                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n                                   File \"/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/authproxy.py\", line 129, in __call__\r\n                                     raise JSONRPCException(response['error'], status)\r\n                                 test_framework.authproxy.JSONRPCException: Internal bug detected: RPC call \"getdescriptorinfo\" returned incorrect type:\r\n                                 {\r\n                                     \"normalized_descriptor\": \"key returned that was not in doc\"\r\n                                 }\r\n                                 Bitcoin Core v26.99.0-504d50bfa3bb-dirty\r\n                                 Please report this issue here: https://github.com/bitcoin/bitcoin/issues\r\n                                  (-1)\r\n```",
      "created_at" : "2024-02-07T13:45:15Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29396#issuecomment-1932083218",
      "id" : 1932083218,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29396",
      "node_id" : "IC_kwDOABII585zKUAS",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1932083218/reactions"
      },
      "updated_at" : "2024-02-07T13:45:15Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1932083218",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/19480819?v=4",
         "events_url" : "https://api.github.com/users/brunoerg/events{/privacy}",
         "followers_url" : "https://api.github.com/users/brunoerg/followers",
         "following_url" : "https://api.github.com/users/brunoerg/following{/other_user}",
         "gists_url" : "https://api.github.com/users/brunoerg/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/brunoerg",
         "id" : 19480819,
         "login" : "brunoerg",
         "node_id" : "MDQ6VXNlcjE5NDgwODE5",
         "organizations_url" : "https://api.github.com/users/brunoerg/orgs",
         "received_events_url" : "https://api.github.com/users/brunoerg/received_events",
         "repos_url" : "https://api.github.com/users/brunoerg/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/brunoerg/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/brunoerg/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/brunoerg"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Concept ACK. To fix the error you need to declare new response field. (see around line no. 183)",
      "created_at" : "2024-02-08T08:06:33Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29396#issuecomment-1933547285",
      "id" : 1933547285,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29396",
      "node_id" : "IC_kwDOABII585zP5cV",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1933547285/reactions"
      },
      "updated_at" : "2024-02-08T08:06:33Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1933547285",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1466284?v=4",
         "events_url" : "https://api.github.com/users/S3RK/events{/privacy}",
         "followers_url" : "https://api.github.com/users/S3RK/followers",
         "following_url" : "https://api.github.com/users/S3RK/following{/other_user}",
         "gists_url" : "https://api.github.com/users/S3RK/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/S3RK",
         "id" : 1466284,
         "login" : "S3RK",
         "node_id" : "MDQ6VXNlcjE0NjYyODQ=",
         "organizations_url" : "https://api.github.com/users/S3RK/orgs",
         "received_events_url" : "https://api.github.com/users/S3RK/received_events",
         "repos_url" : "https://api.github.com/users/S3RK/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/S3RK/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/S3RK/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/S3RK"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "I'm getting an error in one the functional tests cases in `test/functional/rpc_getdescriptorinfo.py`.\r\n\r\nA fix would be changing the derivation path from `1/2h` (hardened) to `1/2` (non-hardened):\r\n\r\n```\r\n-        self.test_desc(\"pkh(tpubD6NzVbkrYhZ4WaWSyoBvQwbpLkojyoTZPRsgXELWz3Popb3qkjcJyJUGLnL4qHHoQvao8ESaAstxYSnhyswJ76uZPStJRJCTKvosUCJZL5B/1h/2)\", isrange=False, issolvable=True, hasprivatekeys=False)\r\n+        self.test_desc(\"pkh(tpubD6NzVbkrYhZ4WaWSyoBvQwbpLkojyoTZPRsgXELWz3Popb3qkjcJyJUGLnL4qHHoQvao8ESaAstxYSnhyswJ76uZPStJRJCTKvosUCJZL5B/1/2)\", isrange=False, issolvable=True, hasprivatekeys=False)\r\n```\r\n\r\nI'm not sure if this change would go against the objectives of the test.",
      "created_at" : "2024-02-09T00:29:50Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29396#issuecomment-1935143088",
      "id" : 1935143088,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29396",
      "node_id" : "IC_kwDOABII585zV_Cw",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1935143088/reactions"
      },
      "updated_at" : "2024-02-09T01:24:44Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1935143088",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/46436462?v=4",
         "events_url" : "https://api.github.com/users/araujo88/events{/privacy}",
         "followers_url" : "https://api.github.com/users/araujo88/followers",
         "following_url" : "https://api.github.com/users/araujo88/following{/other_user}",
         "gists_url" : "https://api.github.com/users/araujo88/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/araujo88",
         "id" : 46436462,
         "login" : "araujo88",
         "node_id" : "MDQ6VXNlcjQ2NDM2NDYy",
         "organizations_url" : "https://api.github.com/users/araujo88/orgs",
         "received_events_url" : "https://api.github.com/users/araujo88/received_events",
         "repos_url" : "https://api.github.com/users/araujo88/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/araujo88/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/araujo88/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/araujo88"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "> I'm getting an error in one the functional tests cases in `test/functional/rpc_getdescriptorinfo.py`.\r\n> \r\n> A fix would be changing the derivation path from `1/2h` (hardened) to `1/2` (non-hardened):\r\n> \r\n> ```\r\n> -        self.test_desc(\"pkh(tpubD6NzVbkrYhZ4WaWSyoBvQwbpLkojyoTZPRsgXELWz3Popb3qkjcJyJUGLnL4qHHoQvao8ESaAstxYSnhyswJ76uZPStJRJCTKvosUCJZL5B/1h/2)\", isrange=False, issolvable=True, hasprivatekeys=False)\r\n> +        self.test_desc(\"pkh(tpubD6NzVbkrYhZ4WaWSyoBvQwbpLkojyoTZPRsgXELWz3Popb3qkjcJyJUGLnL4qHHoQvao8ESaAstxYSnhyswJ76uZPStJRJCTKvosUCJZL5B/1/2)\", isrange=False, issolvable=True, hasprivatekeys=False)\r\n> ```\r\n> \r\n> I'm not sure if this change would go against the objectives of the test.\r\n\r\nYou are adding a new field, existing tests should not fail. That means either your test changes to test the new field are incorrect, or your code is incorrect.",
      "created_at" : "2024-02-09T02:59:51Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29396#issuecomment-1935265831",
      "id" : 1935265831,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29396",
      "node_id" : "IC_kwDOABII585zWdAn",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1935265831/reactions"
      },
      "updated_at" : "2024-02-09T02:59:51Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1935265831",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/3782274?v=4",
         "events_url" : "https://api.github.com/users/achow101/events{/privacy}",
         "followers_url" : "https://api.github.com/users/achow101/followers",
         "following_url" : "https://api.github.com/users/achow101/following{/other_user}",
         "gists_url" : "https://api.github.com/users/achow101/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/achow101",
         "id" : 3782274,
         "login" : "achow101",
         "node_id" : "MDQ6VXNlcjM3ODIyNzQ=",
         "organizations_url" : "https://api.github.com/users/achow101/orgs",
         "received_events_url" : "https://api.github.com/users/achow101/received_events",
         "repos_url" : "https://api.github.com/users/achow101/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/achow101/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/achow101/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/achow101"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "> > I'm getting an error in one the functional tests cases in `test/functional/rpc_getdescriptorinfo.py`.\r\n> > A fix would be changing the derivation path from `1/2h` (hardened) to `1/2` (non-hardened):\r\n> > ```\r\n> > -        self.test_desc(\"pkh(tpubD6NzVbkrYhZ4WaWSyoBvQwbpLkojyoTZPRsgXELWz3Popb3qkjcJyJUGLnL4qHHoQvao8ESaAstxYSnhyswJ76uZPStJRJCTKvosUCJZL5B/1h/2)\", isrange=False, issolvable=True, hasprivatekeys=False)\r\n> > +        self.test_desc(\"pkh(tpubD6NzVbkrYhZ4WaWSyoBvQwbpLkojyoTZPRsgXELWz3Popb3qkjcJyJUGLnL4qHHoQvao8ESaAstxYSnhyswJ76uZPStJRJCTKvosUCJZL5B/1/2)\", isrange=False, issolvable=True, hasprivatekeys=False)\r\n> > ```\r\n> > \r\n> > \r\n> >     \r\n> >       \r\n> >     \r\n> > \r\n> >       \r\n> >     \r\n> > \r\n> >     \r\n> >   \r\n> > I'm not sure if this change would go against the objectives of the test.\r\n> \r\n> You are adding a new field, existing tests should not fail. That means either your test changes to test the new field are incorrect, or your code is incorrect.\r\n\r\nFor the case of hardened derivation path, I guess that instead of throwing a `JSONRPCError` exception, it could simply leave the normalized descriptor field as empty?",
      "created_at" : "2024-02-09T04:25:54Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29396#issuecomment-1935314945",
      "id" : 1935314945,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29396",
      "node_id" : "IC_kwDOABII585zWpAB",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1935314945/reactions"
      },
      "updated_at" : "2024-02-09T04:25:54Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1935314945",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/46436462?v=4",
         "events_url" : "https://api.github.com/users/araujo88/events{/privacy}",
         "followers_url" : "https://api.github.com/users/araujo88/followers",
         "following_url" : "https://api.github.com/users/araujo88/following{/other_user}",
         "gists_url" : "https://api.github.com/users/araujo88/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/araujo88",
         "id" : 46436462,
         "login" : "araujo88",
         "node_id" : "MDQ6VXNlcjQ2NDM2NDYy",
         "organizations_url" : "https://api.github.com/users/araujo88/orgs",
         "received_events_url" : "https://api.github.com/users/araujo88/received_events",
         "repos_url" : "https://api.github.com/users/araujo88/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/araujo88/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/araujo88/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/araujo88"
      }
   }
]
