{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "MEMBER",
   "body" : "https://cirrus-ci.com/task/5692425725804544?logs=ci#L3370:\r\n```bash\r\n node0 2023-12-13T12:44:27.733356Z [httpworker.1] [rpc/request.cpp:187] [parse] [rpc] ThreadRPCServer method=unloadwallet user=__cookie__ \r\n test  2023-12-13T12:44:27.782000Z TestFramework (ERROR): Assertion failed \r\n                                   Traceback (most recent call last):\r\n                                     File \"/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py\", line 131, in main\r\n                                       self.run_test()\r\n                                     File \"/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/wallet_multiwallet.py\", line 292, in run_test\r\n                                       assert_equal(got_loading_error, True)\r\n                                     File \"/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/util.py\", line 57, in assert_equal\r\n                                       raise AssertionError(\"not(%s)\" % \" == \".join(str(arg) for arg in (thing1, thing2) + args))\r\n                                   AssertionError: not(False == True)\r\n test  2023-12-13T12:44:27.784000Z TestFramework (DEBUG): Closing down network thread \r\n test  2023-12-13T12:44:27.834000Z TestFramework (INFO): Stopping nodes \r\n test  2023-12-13T12:44:27.834000Z TestFramework.node0 (DEBUG): Stopping node \r\n node0 stderr Error: Specified -walletdir \"wallets\" is a relative path \r\n node0 stderr bitcoin-node: wallet/wallet.cpp:246: void wallet::UnloadWallet(std::shared_ptr<CWallet> &&): Assertion `it.second' failed. \r\n node0 stderr Warning: Ignoring duplicate -wallet w1. \r\n node0 stderr Error: Specified -walletdir \"wallets\" does not exist \r\n node0 stderr Error: Specified -walletdir \"/ci_container_base/ci/scratch/test_runner/test_runner_â¿_ð_20231213_124140/wallet_multiwallet_255/node0/regtest/wallets/notadir\" is not a directory \r\n node0 stderr Error: BerkeleyDatabase: Can't open database w8_copy (duplicates fileid 378185002c000000dd7bcafdc6f3010000000000 from w8) \r\n node0 stderr Error: Error parsing command line arguments: Invalid parameter -upgradewallet \r\n node0 stderr Error: Specified -walletdir \"bad\" does not exist \r\n node0 stderr Error: Invalid -wallet path 'w8_symlink'. -wallet path should point to a directory where wallet.dat and database/log.?????????? files can be stored, a location where such a directory could be created, or (for backwards compatibility) the name of an existing data file in -walletdir (\"/ci_container_base/ci/scratch/test_runner/test_runner_â¿_ð_20231213_124140/wallet_multiwallet_255/node0/regtest/wallets\") \r\n node0 stderr Error: Specified -walletdir \"debug.log\" is not a directory \r\n node1 stderr Error: Error initializing wallet database environment \"/ci_container_base/ci/scratch/test_runner/test_runner_â¿_ð_20231213_124140/wallet_multiwallet_255/competing_walletdir\"! \r\n```",
   "closed_at" : null,
   "closed_by" : null,
   "comments" : 0,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29073/comments",
   "created_at" : "2023-12-13T12:52:28Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29073/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/29073",
   "id" : 2039651369,
   "labels" : [],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29073/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "I_kwDOABII5855kpwp",
   "number" : 29073,
   "performed_via_github_app" : null,
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29073/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "open",
   "state_reason" : null,
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29073/timeline",
   "title" : "ci: failure in `wallet_multiwallet.py --legacy-wallet`",
   "updated_at" : "2023-12-13T12:52:28Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29073",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/863730?v=4",
      "events_url" : "https://api.github.com/users/fanquake/events{/privacy}",
      "followers_url" : "https://api.github.com/users/fanquake/followers",
      "following_url" : "https://api.github.com/users/fanquake/following{/other_user}",
      "gists_url" : "https://api.github.com/users/fanquake/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/fanquake",
      "id" : 863730,
      "login" : "fanquake",
      "node_id" : "MDQ6VXNlcjg2MzczMA==",
      "organizations_url" : "https://api.github.com/users/fanquake/orgs",
      "received_events_url" : "https://api.github.com/users/fanquake/received_events",
      "repos_url" : "https://api.github.com/users/fanquake/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/fanquake/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/fanquake"
   }
}
